# Generated by Django 3.2.14 on 2022-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0006_remove_sales_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
