# Generated by Django 3.2.14 on 2022-07-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0007_sales_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
