# Generated by Django 3.2.14 on 2022-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0003_auto_20220727_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=2, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
