# Generated by Django 3.2.14 on 2022-07-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0004_auto_20220727_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
