# Generated by Django 3.2.14 on 2022-08-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('products', models.ManyToManyField(to='kafe.Product')),
            ],
        ),
    ]
